### ISSUE TITLE
Deprecation warning while using with NodeJS

### ISSUE THREAD

**Issue by Rajek88** [hoersamu/multi-elo#70]
Hi there! Here is the warning I'm getting, Not sure how to fix it.

(node:6929) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/.........../node_modules/multi-elo/package.json' of 'lib/index.js'. Please either fix that or **report it to the module author**
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by hoersamu** [comment]
fixed in [2.3.1](https://github.com/hoersamu/multi-elo/releases/tag/v2.3.1)
